---
# rubocop styles

require: rubocop-rails

# We will need to improve our Exclude list by removing elements soon
# Excluding vendor/**/* so that CircleCI doesn't check those in their environment
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'app/**/*.json.jbuilder'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# don't use `foo1`, use `foo_1`
Naming/VariableNumber:
  EnforcedStyle: snake_case

# super.match? /simple/
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# attr_reader *%i[one two three ... nine_thousand_and_one]
Lint/AmbiguousOperator:
  Enabled: false

# xml = Nokogiri::XML(File.open file) do |config|
#   ...
# end
#
# Parenthesis are evil.
Style/NestedParenthesizedCalls:
  Enabled: false

# `rescue` is provided for a reason
Style/RescueStandardError:
  Enabled: false

# Who needs module and class comments anyway?
Style/Documentation:
  Enabled: false

# Hash rockets for everything
Style/HashSyntax:
  EnforcedStyle: hash_rockets
  UseHashRocketsWithSymbolValues: true
  PreferHashRocketsForNonAlnumEndingSymbols: true

# {:foo => :bar} instead of  { :foo => :bar }
# {} is for hashes
# { } is for blocks
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Always use <<~HERE
# HERE
Layout/HeredocIndentation:
  EnforcedStyle: squiggly

# Rake tasks usually end up having no respect for line lengths.
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
Layout/LineLength:
  Exclude:
    - 'Rakefile'
    - '**/*.erb'
    - '**/*.html.haml'
    - '**/*.rake'
  Max: 120
Metrics/MethodLength:
  Max: 20

# describe Samsquanch do
#   ...
# end # describe Samsquanch
Style/CommentedKeyword:
  Enabled: false

# {
#   :a_key => 1,
#   :a_longer_key => 2
# }
Layout/HashAlignment:
  EnforcedHashRocketStyle: key

Layout/LeadingCommentSpace:
  Exclude:
    - 'locale/**/*'

# String abuse is a crime, punishable by Ruby 3
Style/FrozenStringLiteralComment:
  Enabled: false

# always use `-> () { }`
Style/Lambda:
  EnforcedStyle: literal

# always add space between stabby lambda and args
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

#################################################
# RAILS COPS
#################################################

Rails/HasManyOrHasOneDependent:
  Enabled: false
